# Generated by Django 2.2.10 on 2020-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200331_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(help_text='Выберите жанры, которые представляет автор', to='catalog.Genre'),
        ),
    ]
