# Generated by Django 2.2.10 on 2020-04-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_image_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ForeignKey(help_text='Выберите жанры, которые представляет автор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre'),
        ),
    ]
